#lang info
(define collection 'multi)
(define deps
  (list "lux"
        "dos"
        "fector"
        "opengl"
        "base"
        "compatibility-lib"
        "data-lib"
        "data-enumerate-lib"
        "draw-lib"
        "eli-tester"
        "gui-lib"
        "htdp-lib"
        "math"
        "pfds"
        "plot"
        "rackunit-lib"
        "redex-lib"
        "mode-lambda"
        "apse"
        "slideshow-lib"
        "typed-racket-lib"
        "unstable-list-lib"
        "racket-doc"))
